[PPP-5353]-XSS Findings For Pentaho-platform-plugin-reporting
pentaho/pentaho-platform-plugin-reporting pull request #864
Opened 2024-11-06 10:27 UTC by Rangashivani

[PPP-5353]-XSS Findings For Pentaho-platform-plugin-reporting

2024-11-06 10:32 UTC, buildguy commented
[comment]: <> (FrogbotReviewComment)

<div align='center'>

[![👍 Frogbot scanned this pull request and did not find any new security issues.](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/noVulnerabilityBannerPR.png)](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

2024-11-06 10:32 UTC, buildguy commented
### :white_check_mark: Build finished in 4m 50s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl core
```
---
:ok_hand: All tests passed!
 
Tests run: **540**, Failures: **0**, Skipped: **3** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform-reporting-plugin/job/PR-864/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2024-11-06 14:30 UTC, dcleao commented on core/src/main/javascript/reportviewer/dojo/pentaho/reportviewer/GlassPane.js
> +"pentaho/common/button", "pentaho/common/Dialog", "dojo/text!pentaho/reportviewer/GlassPane.html","common-ui/util/xss"],
Missing space after comma.

2024-11-06 18:14 UTC, dcleao requested changes

2024-11-06 18:14 UTC, dcleao commented on core/src/main/javascript/reportviewer/reportviewer.js
> +                    xssUtil.setHtml($('notification-message'), _Messages.getString('LoadingPage') + " " + mainJobStatus.page + " " + _Messages.getString('Of') + " " + mainJobStatus.totalPages);
I can't find the comment from another PR review where I wrote this, so I'm repeating here.

Note that the query selector passed to jQuery should remain as `#notification-message`.

The XSS Utility `setHtml(elem, html)` method does not support jQuery objects in the first argument, only actual `HTMLElement`.

On the other hand, if we keep using the pattern `$('#notification-message').html(xssUtil.sanitizeHtml(html))` with jQuery instances, likely, the corresponding AppScan findings will not be automatically resolved.

As such, we should consider adding support for jQuery objects to the existing `setHtml(..)` method, and then use it with these jQuery cases.

2024-11-06 18:14 UTC, dcleao commented on core/src/main/javascript/reportviewer/reportviewer.js
> +                    xssUtil.setHtml($('#notification-message'), _Messages.getString('LoadingPage') + " " + mainJobStatus.page + " " + _Messages.getString('Of') + " " + mainJobStatus.totalPages);
Idem, regarding adding jQuery support to `setHtml(..)`.

2024-11-06 18:14 UTC, dcleao commented on core/src/main/javascript/reportviewer/reportviewer.js
> +                  xssUtil.setHtml($('#notification-message'), _Messages.getString('LoadingPage') + " " + mainJobStatus.page + " " + _Messages.getString('Of') + " " + mainJobStatus.totalPages);
Idem, regarding adding jQuery support to `setHtml(..)`.

2024-11-06 18:14 UTC, dcleao commented on core/src/main/javascript/reportviewer/reportviewer.js
> +                  xssUtil.setHtml($('#notification-message'), _Messages.getString('LoadingPage') + " " + mainJobStatus.page + " " + _Messages.getString('Of') + " " + mainJobStatus.totalPages);
Idem, regarding adding jQuery support to `setHtml(..)`.

2024-11-07 12:07 UTC, buildguy commented
[comment]: <> (FrogbotReviewComment)

<div align='center'>

[![👍 Frogbot scanned this pull request and did not find any new security issues.](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/noVulnerabilityBannerPR.png)](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

2024-11-07 12:08 UTC, buildguy commented
### :white_check_mark: Build finished in 5m 58s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl core
```
---
:ok_hand: All tests passed!
 
Tests run: **540**, Failures: **0**, Skipped: **3** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform-reporting-plugin/job/PR-864/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2024-11-13 10:25 UTC, closed without merging